// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfPIsZQz_gp8t5qLIsbZvfIytOXP6mnJE',
    appId: '1:173824635947:web:086c8143e334ad4bc6a66e',
    messagingSenderId: '173824635947',
    projectId: 'act14-16f7c',
    authDomain: 'act14-16f7c.firebaseapp.com',
    storageBucket: 'act14-16f7c.firebasestorage.app',
    measurementId: 'G-Y735XZ32R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg0iKaviqf5aBxHHRjHt7WjWRxGukiCow',
    appId: '1:173824635947:android:3eed2410aca5fd46c6a66e',
    messagingSenderId: '173824635947',
    projectId: 'act14-16f7c',
    storageBucket: 'act14-16f7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_D5UHR9Pu0xtztcn_ZttDW7ylN3JklUQ',
    appId: '1:173824635947:ios:306435478492bb96c6a66e',
    messagingSenderId: '173824635947',
    projectId: 'act14-16f7c',
    storageBucket: 'act14-16f7c.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_D5UHR9Pu0xtztcn_ZttDW7ylN3JklUQ',
    appId: '1:173824635947:ios:306435478492bb96c6a66e',
    messagingSenderId: '173824635947',
    projectId: 'act14-16f7c',
    storageBucket: 'act14-16f7c.firebasestorage.app',
    iosBundleId: 'com.example.act14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfPIsZQz_gp8t5qLIsbZvfIytOXP6mnJE',
    appId: '1:173824635947:web:8b945d74c98317ccc6a66e',
    messagingSenderId: '173824635947',
    projectId: 'act14-16f7c',
    authDomain: 'act14-16f7c.firebaseapp.com',
    storageBucket: 'act14-16f7c.firebasestorage.app',
    measurementId: 'G-2S7K3WC9NS',
  );
}
